version: '3.9'
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 4000:4000
  db:
    image: postgres
    ports:
      - 4321:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nextauthdb
  #    volumes:
  #      - mongo-data:/data/db
  #  mongo-express:
  #    image: mongo-express
  #    ports:
  #      - 8080:8081
  #    environment:
  #      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  #      - ME_CONFIG_MONGODB_SERVER=mongodb
  #volumes:
  #  mongo-data:
  #    driver: local
